openapi: 3.0.0
info:
  title: Product Microservice
  description: Product Microservice
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /products:
    post:
      tags:
        - product
      summary: Add a new product to the database
      description: Add a new product to the database
      operationId: addProduct
      requestBody:
        description: Create a new product in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "405":
          description: Invalid input
    get:
      tags:
        - product
      summary: Get list of products
      description: Retrieve a list of all products
      operationId: getProducts
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "404":
          description: Products not found
  /products/{id}:
    get:
      tags:
        - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: ID of product to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - code
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          description: Name of the product
        code:
          type: string
          description: Code of the product
      xml:
        name: product
